Repository mesosphere/spark-build, pull requests merged in 2018-07, with the labels that each got.

#366 [DOCUMENTATION][DCOS-37661] Add notes on backing up dashboards to monitoring README
  monitoring/README.md
Labels: ready for review

#376 [DCOS-39086] Prepare Spark scale test parameters file for 2018-07-11
  scale-tests/configs/2018-07-11-kafka110s-small-scale.env
  scale-tests/configs/2018-07-11-mvrandom110-full-scale.env
Labels: ready for review

#381 Fix janitor zk node path.
  scale-tests/uninstall-dispatchers.sh
Labels: ready for review

#384 [COPS-3443] Make default docker image the one in resource.json
  universe/config.json
Labels: ready for review

#371 Update JRE to 1.8.172 (#369)
  docker/Dockerfile
  universe/marathon.json.mustache
Labels: backport

#372 Update bootstrap to 0.50.0 (#368)
  conf/spark-env.sh
  docker/Dockerfile
Labels: backport

#385 [COPS-3443] Make default docker image the one in resource.json (#384)
  universe/config.json
Labels: backport, ready for review
